before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Je6CicryFUclHkhwp30hL442/f65p/HtClmLP5yPB+HKCXJhPk209XaelLal+fyMU74xVPooAk8knLj/qB6W2e81IIoacuIvUGYK0pV2gdm2AykNOENz5huez6LoTBAigiD/A8yo6jgs605wqo4XXzKlEv9TKv03NnGv59aD24Bh7R6VO2eyf4TbijvnmrTfqwnX5cV3JyTBTR8HkBr4ZJBwtm2gkf0Kbl6kZausD5Va78bZBKFjziyLdjAyDlO1OntukfiUIpuuwtpeQiQ2EtEC8A132iJVdLY2Yl+9MFW7naOHFnKUJ++sg3H/7PB2jzuzwl7d6UKsBhntYxLpLISG/8UjMl7Nym+fD/oIv00ZetQ5BYVNt0uB9pKUOYK2ivbiMYkZkTzBmZ/FqAedKFfnBVArfCqefbfGz0MeK+t7+Bnh0syXv+KQXgYYWZGXuYK6qvtus6wqgeJoYKni+ZkZKsWRaXSLtWMkioOuQW/1SEOz4lWe4wz7+swa3SjtNDiXBAcoO4kDYabEiH+92+w1GrYN/m10C3uxmm8Qgqnenfcz7ryVmO0NXDFsU2C9Uau8cfXx4osjzpljyTLqoITUWdR0xevb7q9vMxpobkZUWktPM3tyboS8ic6YsKWHqlUCEuiH/UT2/z/Q3Gk8BigAVW/lVN2JQ2VvscUV5Xs= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
